/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaBase_oopExample_nativeExample_HelloJNI */

#ifndef _Included_JavaBase_oopExample_nativeExample_HelloJNI
#define _Included_JavaBase_oopExample_nativeExample_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaBase_oopExample_nativeExample_HelloJNI
 * Method:    helloJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaBase_oopExample_nativeExample_HelloJNI_helloJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
